import { Business } from "@/types"

export const featuredBusinesses: Business[] = [
  {
    id: "1",
    name: "Spice Garden Restaurant",
    category: "Restaurants",
    subcategory: "South Indian",
    description: "Authentic South Indian cuisine with traditional recipes passed down through generations.",
    address: "12, MG Road, Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500034",
    phone: "+91 98765 43210",
    email: "info@spicegarden.com",
    website: "www.spicegarden.com",
    rating: 4.5,
    reviewCount: 234,
    isVerified: true,
    isFeatured: true,
    images: [],
    lat: 17.385,
    lng: 78.4867,
    openNow: true,
    timings: "8:00 AM - 11:00 PM",
  },
  {
    id: "2",
    name: "Dr. Sharma Multispeciality Clinic",
    category: "Healthcare",
    subcategory: "General Physician",
    description: "15+ years of experience in general medicine, diabetes, and preventive healthcare.",
    address: "45, Jubilee Hills Road No. 36",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500033",
    phone: "+91 98765 11111",
    email: "drsharma@clinic.com",
    rating: 4.8,
    reviewCount: 412,
    isVerified: true,
    isFeatured: true,
    images: [],
    lat: 17.4326,
    lng: 78.4071,
    openNow: true,
    timings: "9:00 AM - 7:00 PM",
  },
  {
    id: "3",
    name: "Glamour Studio Salon",
    category: "Beauty & Wellness",
    subcategory: "Unisex Salon",
    description: "Premium salon experience with expert stylists, skincare and bridal packages.",
    address: "8, Kondapur Main Road",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500084",
    phone: "+91 98765 22222",
    rating: 4.3,
    reviewCount: 187,
    isVerified: true,
    isFeatured: true,
    images: [],
    lat: 17.4604,
    lng: 78.3575,
    openNow: false,
    timings: "10:00 AM - 8:00 PM",
  },
  {
    id: "4",
    name: "Mumbai Tiffin House",
    category: "Restaurants",
    subcategory: "North Indian",
    description: "Home-style tiffin and thali meals, loved by office goers across the city.",
    address: "22, Andheri West, Link Road",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400058",
    phone: "+91 98765 33333",
    rating: 4.6,
    reviewCount: 521,
    isVerified: true,
    isFeatured: true,
    images: [],
    lat: 19.1334,
    lng: 72.8267,
    openNow: true,
    timings: "7:00 AM - 10:00 PM",
  },
  {
    id: "5",
    name: "TechFix Computer Services",
    category: "IT Services",
    subcategory: "Computer Repair",
    description: "Laptop, desktop repair, networking, and AMC services for home and businesses.",
    address: "56, Brigade Road",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560025",
    phone: "+91 98765 44444",
    rating: 4.4,
    reviewCount: 98,
    isVerified: true,
    isFeatured: true,
    images: [],
    lat: 12.9716,
    lng: 77.5946,
    openNow: true,
    timings: "9:00 AM - 9:00 PM",
  },
  {
    id: "6",
    name: "Royal Caterers",
    category: "Catering Services",
    subcategory: "Wedding & Events",
    description: "Premium catering for weddings, corporate events and social gatherings across Delhi NCR.",
    address: "14, Karol Bagh",
    city: "Delhi",
    state: "Delhi",
    pincode: "110005",
    phone: "+91 98765 55555",
    email: "royal@caterers.com",
    rating: 4.7,
    reviewCount: 310,
    isVerified: true,
    isFeatured: true,
    images: [],
    lat: 28.6519,
    lng: 77.1909,
    openNow: true,
    timings: "9:00 AM - 8:00 PM",
  },
]