import { Category } from "@/types"

export const categories: Category[] = [
  { id: "1", name: "Restaurants", icon: "utensils", count: 45230, slug: "restaurants" },
  { id: "2", name: "Healthcare", icon: "heart-pulse", count: 32100, slug: "healthcare" },
  { id: "3", name: "Beauty Salon", icon: "scissors", count: 28900, slug: "beauty-salon" },
  { id: "4", name: "Automotive Services", icon: "car", count: 22400, slug: "automotive-services" },
  { id: "5", name: "Education & Training", icon: "graduation-cap", count: 31200, slug: "education-training" },
  { id: "6", name: "Pharmacy", icon: "pill", count: 22300, slug: "pharmacy" },
  { id: "7", name: "Electrical Services", icon: "zap", count: 11200, slug: "electrical-services" },
  { id: "8", name: "Real Estate", icon: "building-2", count: 18700, slug: "real-estate" },
  { id: "9", name: "Financial Services", icon: "landmark", count: 14500, slug: "financial-services" },
  { id: "10", name: "Grocery Store", icon: "shopping-cart", count: 19600, slug: "grocery-store" },
  { id: "11", name: "Fitness & Wellness", icon: "dumbbell", count: 9800, slug: "fitness-wellness" },
  { id: "12", name: "IT Services", icon: "laptop", count: 16300, slug: "it-services" },
  { id: "13", name: "Travel Agency", icon: "plane", count: 7800, slug: "travel-agency" },
  { id: "14", name: "Wedding Planning", icon: "heart", count: 8600, slug: "wedding-planning" },
  { id: "15", name: "Catering Services", icon: "chef-hat", count: 12100, slug: "catering-services" },
  { id: "16", name: "Construction", icon: "hard-hat", count: 16300, slug: "construction" },
  { id: "17", name: "Courier & Logistics", icon: "package", count: 9400, slug: "courier-logistics" },
  { id: "18", name: "Digital Marketing", icon: "megaphone", count: 8600, slug: "digital-marketing" },
]

export const allCategories: Category[] = [
  { id: "1", name: "Accommodation Services", icon: "bed", count: 4200, slug: "accommodation-services" },
  { id: "2", name: "Accounting & Financial Services", icon: "calculator", count: 6100, slug: "accounting-financial" },
  { id: "3", name: "Agriculture & Farming", icon: "tractor", count: 3200, slug: "agriculture-farming" },
  { id: "4", name: "Air Conditioning & Refrigeration", icon: "wind", count: 5400, slug: "ac-refrigeration" },
  { id: "5", name: "Apparel & Fashion", icon: "shirt", count: 8900, slug: "apparel-fashion" },
  { id: "6", name: "Arts & Crafts", icon: "palette", count: 3100, slug: "arts-crafts" },
  { id: "7", name: "Astrology & Spiritual Guidance", icon: "star", count: 2800, slug: "astrology-spiritual" },
  { id: "8", name: "Automotive Services", icon: "car", count: 22400, slug: "automotive-services" },
  { id: "9", name: "Ayurveda & Wellness", icon: "leaf", count: 4600, slug: "ayurveda-wellness" },
  { id: "10", name: "Beauty & Wellness", icon: "sparkles", count: 28900, slug: "beauty-wellness" },
  { id: "11", name: "Business Consulting", icon: "briefcase", count: 7200, slug: "business-consulting" },
  { id: "12", name: "Catering Services", icon: "chef-hat", count: 12100, slug: "catering-services" },
  { id: "13", name: "Computer Repair & Services", icon: "monitor", count: 9300, slug: "computer-repair" },
  { id: "14", name: "Construction", icon: "hard-hat", count: 16300, slug: "construction" },
  { id: "15", name: "Courier & Logistics", icon: "package", count: 9400, slug: "courier-logistics" },
  { id: "16", name: "Dairy & Products", icon: "milk", count: 3800, slug: "dairy-products" },
  { id: "17", name: "Digital Marketing", icon: "megaphone", count: 8600, slug: "digital-marketing" },
  { id: "18", name: "Driving School", icon: "car", count: 4100, slug: "driving-school" },
  { id: "19", name: "Education & Training", icon: "graduation-cap", count: 31200, slug: "education-training" },
  { id: "20", name: "Electrical Services", icon: "zap", count: 11200, slug: "electrical-services" },
  { id: "21", name: "Electronics Retail", icon: "cpu", count: 14300, slug: "electronics-retail" },
  { id: "22", name: "Event Planning", icon: "calendar", count: 6700, slug: "event-planning" },
  { id: "23", name: "Financial Services", icon: "landmark", count: 14500, slug: "financial-services" },
  { id: "24", name: "Fitness & Recreation", icon: "dumbbell", count: 9800, slug: "fitness-recreation" },
  { id: "25", name: "Food & Beverage", icon: "utensils", count: 45230, slug: "food-beverage" },
  { id: "26", name: "Furniture Retail", icon: "armchair", count: 7600, slug: "furniture-retail" },
  { id: "27", name: "Government Services", icon: "building", count: 2400, slug: "government-services" },
  { id: "28", name: "Grocery Store", icon: "shopping-cart", count: 19600, slug: "grocery-store" },
  { id: "29", name: "Hardware Store", icon: "wrench", count: 8900, slug: "hardware-store" },
  { id: "30", name: "Healthcare", icon: "heart-pulse", count: 32100, slug: "healthcare" },
  { id: "31", name: "Home Services", icon: "home", count: 21400, slug: "home-services" },
  { id: "32", name: "Hospitality", icon: "hotel", count: 18700, slug: "hospitality" },
  { id: "33", name: "Insurance", icon: "shield", count: 6300, slug: "insurance" },
  { id: "34", name: "Interior Design", icon: "layout", count: 5800, slug: "interior-design" },
  { id: "35", name: "IT Services", icon: "laptop", count: 16300, slug: "it-services" },
  { id: "36", name: "Jewelry & Precious Stones", icon: "gem", count: 7200, slug: "jewelry" },
  { id: "37", name: "Massage Therapy", icon: "hand", count: 4100, slug: "massage-therapy" },
  { id: "38", name: "Mobile Phone Repair", icon: "smartphone", count: 11800, slug: "mobile-repair" },
  { id: "39", name: "Music Education", icon: "music", count: 3600, slug: "music-education" },
  { id: "40", name: "Optical Services", icon: "eye", count: 6900, slug: "optical-services" },
  { id: "41", name: "Pest Control", icon: "bug", count: 4800, slug: "pest-control" },
  { id: "42", name: "Pet Services", icon: "paw-print", count: 3200, slug: "pet-services" },
  { id: "43", name: "Pharmacy", icon: "pill", count: 22300, slug: "pharmacy" },
  { id: "44", name: "Photography", icon: "camera", count: 7400, slug: "photography" },
  { id: "45", name: "Printing Services", icon: "printer", count: 5600, slug: "printing-services" },
  { id: "46", name: "Real Estate", icon: "building-2", count: 18700, slug: "real-estate" },
  { id: "47", name: "Restaurants", icon: "utensils", count: 45230, slug: "restaurants" },
  { id: "48", name: "Retail", icon: "store", count: 32400, slug: "retail" },
  { id: "49", name: "Telecommunications", icon: "phone", count: 8100, slug: "telecommunications" },
  { id: "50", name: "Travel Agency", icon: "plane", count: 7800, slug: "travel-agency" },
  { id: "51", name: "Transportation", icon: "truck", count: 9200, slug: "transportation" },
  { id: "52", name: "Web Development", icon: "code", count: 6400, slug: "web-development" },
  { id: "53", name: "Wedding Planning", icon: "heart", count: 8600, slug: "wedding-planning" },
  { id: "54", name: "Wholesale & Retail Trading", icon: "shopping-bag", count: 11300, slug: "wholesale-retail" },
]